---
- name: Install dependencies for building ruby on CentOS
  yum:
    state: present
    name:
      - epel-release
      - gcc
      - gcc-c++
      - make
      - curl
      - git-core
      - libcurl-devel
      - libffi-devel
      - jemalloc-devel
      - readline-devel
      - sqlite-devel
      - openssl-devel
      - libxml2-devel
      - libxslt-devel
      - libyaml-devel
      - zlib-devel
